Executing: pytest -c /home/kolby/ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ/GitHub/execution-spec-tests/src/cli/pytest_commands/pytest_ini_files/pytest-execute.ini --rootdir . --fork=Prague --rpc-endpoint=http://127.0.0.1:8547 
--rpc-seed-key 0xb6b15c8cb491557369f3c7d2c287b053eb229daa9c22138887752191c9520659 --rpc-chain-id 412346 ./tests/cancun/eip1153_tstore --verbose
============================= test session starts ==============================
platform linux -- Python 3.11.13, pytest-8.4.1, pluggy-1.6.0 -- /home/kolby/ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ/GitHub/execution-spec-tests/.venv/bin/python3
[1mGenerating fixtures for: Prague[39;49m
[1m[93mOnly generating fixtures with stable/deployed forks: Specify an upcoming fork via --until=fork to add forks under development.[39;49m
[1mStart seed for EOA: 0x21a6f548723c83438e639f47f813f01b6c96259855b28b64f4e9d1623ba1acec [39;49m
cachedir: .pytest_cache
metadata: {'Python': '3.11.13', 'Platform': 'Linux-6.14.0-28-generic-x86_64-with-glibc2.41', 'Packages': {'pytest': '8.4.1', 'pluggy': '1.6.0'}, 'Plugins': {'json-report': '1.5.0', 'custom-report': '1.0.1', 'regex': '0.2.0', 'xdist': '3.8.0', 'metadata': '3.1.1', 'cov': '4.1.0', 'html': '4.1.1'}, 'Command-line args': '<code>fill -c /home/kolby/ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ/GitHub/execution-spec-tests/src/cli/pytest_commands/pytest_ini_files/pytest-execute.ini --rootdir . --fork=Prague --rpc-endpoint=http://127.0.0.1:8547 --rpc-seed-key 0xb6b15c8cb491557369f3c7d2c287b053eb229daa9c22138887752191c9520659 --rpc-chain-id 412346 ./tests/cancun/eip1153_tstore --verbose</code>', 'Senders': {}}
rootdir: /home/kolby/ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ/GitHub/execution-spec-tests
configfile: src/cli/pytest_commands/pytest_ini_files/pytest-execute.ini
plugins: json-report-1.5.0, custom-report-1.0.1, regex-0.2.0, xdist-3.8.0, metadata-3.1.1, cov-4.1.0, html-4.1.1
collecting ...  pytest-regex selected 125 tests to run for regex: .*
collected 125 items

tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_transaction_begin[fork_Prague-state_test] FAILED [  1/125]
tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_works[fork_Prague-state_test] FAILED [  2/125]
tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_other_after_tstore[fork_Prague-state_test] FAILED [  3/125]
tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_gasprice[fork_Prague-state_test] FAILED [  4/125]
tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_after_store[fork_Prague-state_test] FAILED [  5/125]
tests/cancun/eip1153_tstore/test_tload_calls.py::test_tload_calls[fork_Prague-state_test-call_type_CALL] FAILED [  6/125]
tests/cancun/eip1153_tstore/test_tload_calls.py::test_tload_calls[fork_Prague-state_test-call_type_CALLCODE] FAILED [  7/125]
tests/cancun/eip1153_tstore/test_tload_calls.py::test_tload_calls[fork_Prague-state_test-call_type_DELEGATECALL] FAILED [  8/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALL] FAILED [  9/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALLCODE] FAILED [ 10/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_DELEGATECALL] FAILED [ 11/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_STATICCALL] FAILED [ 12/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALL] FAILED [ 13/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALLCODE] FAILED [ 14/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_DELEGATECALL] FAILED [ 15/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_STATICCALL] FAILED [ 16/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALL] FAILED [ 17/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALLCODE] FAILED [ 18/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_DELEGATECALL] FAILED [ 19/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_STATICCALL] FAILED [ 20/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALL] FAILED [ 21/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALLCODE] FAILED [ 22/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_DELEGATECALL] FAILED [ 23/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_STATICCALL] FAILED [ 24/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALL] FAILED [ 25/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALLCODE] FAILED [ 26/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_DELEGATECALL] FAILED [ 27/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_STATICCALL] FAILED [ 28/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALL] FAILED [ 29/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALLCODE] FAILED [ 30/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_DELEGATECALL] FAILED [ 31/125]
tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_STATICCALL] FAILED [ 32/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_transient_storage_unset_values[fork_Prague-state_test] PASSED [ 33/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_tload_after_tstore[fork_Prague-state_test] PASSED [ 34/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_tload_after_sstore[fork_Prague-state_test] PASSED [ 35/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_tload_after_tstore_is_zero[fork_Prague-state_test] PASSED [ 36/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_gas_usage[fork_Prague-state_test-tload] PASSED [ 37/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_gas_usage[fork_Prague-state_test-tstore_tload] PASSED [ 38/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_gas_usage[fork_Prague-state_test-tstore_cold] PASSED [ 39/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_gas_usage[fork_Prague-state_test-tstore_warm] PASSED [ 40/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_run_until_out_of_gas[fork_Prague-tx_gas_limit_0x0112a880-state_test-tstore] PASSED [ 41/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_run_until_out_of_gas[fork_Prague-tx_gas_limit_0x0112a880-state_test-tstore_wide_address_space] PASSED [ 42/125]
tests/cancun/eip1153_tstore/test_tstorage.py::test_run_until_out_of_gas[fork_Prague-tx_gas_limit_0x0112a880-state_test-tstore_tload] PASSED [ 43/125]
tests/cancun/eip1153_tstore/test_tstorage_clear_after_tx.py::test_tstore_clear_after_deployment_tx[fork_Prague-evm_code_type_LEGACY-blockchain_test] PASSED [ 44/125]
tests/cancun/eip1153_tstore/test_tstorage_clear_after_tx.py::test_tstore_clear_after_tx[fork_Prague-evm_code_type_LEGACY-blockchain_test] PASSED [ 45/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-only_constructor_code-create] PASSED [ 46/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-only_constructor_code-create2] PASSED [ 47/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-in_constructor_and_deployed_code-create] PASSED [ 48/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-in_constructor_and_deployed_code-create2] PASSED [ 49/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-across_constructor_and_deployed_code_v0-create] PASSED [ 50/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-across_constructor_and_deployed_code_v0-create2] PASSED [ 51/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-across_constructor_and_deployed_code_v1-create] PASSED [ 52/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-across_constructor_and_deployed_code_v1-create2] PASSED [ 53/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-no_constructor_code-create] PASSED [ 54/125]
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py::TestTransientStorageInContractCreation::test_contract_creation[fork_Prague-state_test-no_constructor_code-create2] PASSED [ 55/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-call] PASSED [ 56/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-staticcall_cant_call_tstore] PASSED [ 57/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-staticcall_cant_call_tstore_with_stack_underflow] PASSED [ 58/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-staticcalled_context_can_call_tload] PASSED [ 59/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-callcode] PASSED [ 60/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-delegatecall] PASSED [ 61/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-call_with_revert] PASSED [ 62/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-call_with_invalid] PASSED [ 63/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-call_with_stack_overflow] PASSED [ 64/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-call_with_tstore_stack_underflow] PASSED [ 65/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-call_with_tstore_stack_underflow_2] PASSED [ 66/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-call_with_tload_stack_underflow] PASSED [ 67/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-call_with_out_of_gas] PASSED [ 68/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-call_with_out_of_gas_2] PASSED [ 69/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-callcode_with_revert] PASSED [ 70/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-callcode_with_invalid] PASSED [ 71/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-callcode_with_stack_overflow] PASSED [ 72/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-callcode_with_tstore_stack_underflow] PASSED [ 73/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-callcode_with_tstore_stack_underflow_2] PASSED [ 74/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-callcode_with_tload_stack_underflow] PASSED [ 75/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-callcode_with_out_of_gas] PASSED [ 76/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-callcode_with_out_of_gas_2] PASSED [ 77/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-delegatecall_with_revert] PASSED [ 78/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-delegatecall_with_invalid] PASSED [ 79/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-delegatecall_with_stack_overflow] PASSED [ 80/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-delegatecall_with_tstore_stack_underflow] PASSED [ 81/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-delegatecall_with_tstore_stack_underflow_2] PASSED [ 82/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-delegatecall_with_tload_stack_underflow] PASSED [ 83/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-delegatecall_with_out_of_gas] PASSED [ 84/125]
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py::test_subcall[fork_Prague-state_test-delegatecall_with_out_of_gas_2] PASSED [ 85/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-tstore_in_reentrant_call] PASSED [ 86/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-tload_after_reentrant_tstore] PASSED [ 87/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-manipulate_in_reentrant_call] PASSED [ 88/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-tstore_in_call_then_tload_return_in_staticcall] PASSED [ 89/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-tstore_before_revert_has_no_effect] PASSED [ 90/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-revert_undoes_all] PASSED [ 91/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-revert_undoes_tstorage_after_successful_call] PASSED [ 92/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-tstore_before_invalid_has_no_effect] PASSED [ 93/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-invalid_undoes_all] PASSED [ 94/125]
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py::test_reentrant_call[fork_Prague-state_test-invalid_undoes_tstorage_after_successful_call] PASSED [ 95/125]
tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py::test_reentrant_selfdestructing_call[fork_Prague-state_test-tload_after_selfdestruct_pre_existing_contract] PASSED [ 96/125]
tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py::test_reentrant_selfdestructing_call[fork_Prague-state_test-tload_after_selfdestruct_new_contract] PASSED [ 97/125]
tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py::test_reentrant_selfdestructing_call[fork_Prague-state_test-tload_after_inner_selfdestruct_pre_existing_contract] PASSED [ 98/125]
tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py::test_reentrant_selfdestructing_call[fork_Prague-state_test-tload_after_inner_selfdestruct_new_contract] PASSED [ 99/125]
tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py::test_reentrant_selfdestructing_call[fork_Prague-state_test-tstore_after_selfdestruct_pre_existing_contract] PASSED [100/125]
tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py::test_reentrant_selfdestructing_call[fork_Prague-state_test-tstore_after_selfdestruct_new_contract] PASSED [101/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALL] FAILED [102/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALLCODE] FAILED [103/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_DELEGATECALL] FAILED [104/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_STATICCALL] FAILED [105/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALL] FAILED [106/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALLCODE] FAILED [107/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_DELEGATECALL] FAILED [108/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_STATICCALL] FAILED [109/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALL] FAILED [110/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALLCODE] FAILED [111/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_DELEGATECALL] FAILED [112/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_STATICCALL] FAILED [113/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALL] FAILED [114/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALLCODE] FAILED [115/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_DELEGATECALL] FAILED [116/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_STATICCALL] FAILED [117/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALL] FAILED [118/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALLCODE] FAILED [119/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_DELEGATECALL] FAILED [120/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_STATICCALL] FAILED [121/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALL] FAILED [122/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALLCODE] FAILED [123/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_DELEGATECALL] FAILED [124/125]
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_STATICCALL] FAILED [125/125]

=================================== FAILURES ===================================
__________ test_basic_tload_transaction_begin[fork_Prague-state_test] __________
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x663237C642a9F88dc03Eb7a3B1F6fb77A168aD0E, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_basic_tload.py:67: in test_basic_tload_transaction_begin
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x663237C642a9F88dc03Eb7a3B1F6fb77A168aD0E, maxFeePerGas: 10 baseFee: 100000000)
---------------------------- Captured stdout setup -----------------------------
Starting EOA index: 0x21a6f548723c83438e639f47f813f01b6c96259855b28b64f4e9d1623ba1acec
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 156830
--------------------------- Captured stdout teardown ---------------------------
Used balance=0.000030894400000000
________________ test_basic_tload_works[fork_Prague-state_test] ________________
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x86264C7cF6a312CEe5Dbee36CE76FD472737A8C1, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_basic_tload.py:125: in test_basic_tload_works
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x86264C7cF6a312CEe5Dbee36CE76FD472737A8C1, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 206924
--------------------------- Captured stdout teardown ---------------------------
Used balance=0.000033349600000000
_________ test_basic_tload_other_after_tstore[fork_Prague-state_test] __________
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x2391f895879436c23B1b92836Adf93F6581f8Bac, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_basic_tload.py:179: in test_basic_tload_other_after_tstore
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x2391f895879436c23B1b92836Adf93F6581f8Bac, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 158996
--------------------------- Captured stdout teardown ---------------------------
Used balance=0.000031002600000000
______________ test_basic_tload_gasprice[fork_Prague-state_test] _______________
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x34A8AA4802289fc2FAb04cE28f00442BCCe9a84f, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_basic_tload.py:263: in test_basic_tload_gasprice
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x34A8AA4802289fc2FAb04cE28f00442BCCe9a84f, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 229322
--------------------------- Captured stdout teardown ---------------------------
Used balance=0.000034470600000000
_____________ test_basic_tload_after_store[fork_Prague-state_test] _____________
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x4e4e856Ff771942246A4d2CE4dEB7A97002e92aE, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_basic_tload.py:314: in test_basic_tload_after_store
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x4e4e856Ff771942246A4d2CE4dEB7A97002e92aE, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 159020
--------------------------- Captured stdout teardown ---------------------------
Used balance=0.000031003800000000
___________ test_tload_calls[fork_Prague-state_test-call_type_CALL] ____________
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x9E1a539A1e7Da203C7AEDD9F605Df8EA3Daf86D2, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_calls.py:99: in test_tload_calls
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x9E1a539A1e7Da203C7AEDD9F605Df8EA3Daf86D2, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 204740
Deploying contract with gas limit: 217586
--------------------------- Captured stdout teardown ---------------------------
Used balance=2.000044023600000109
_________ test_tload_calls[fork_Prague-state_test-call_type_CALLCODE] __________
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xdDA55060DFa783467F89F351D6d92F753F659D4F, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_calls.py:99: in test_tload_calls
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xdDA55060DFa783467F89F351D6d92F753F659D4F, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 204740
Deploying contract with gas limit: 217586
--------------------------- Captured stdout teardown ---------------------------
Used balance=2.000044023600000109
_______ test_tload_calls[fork_Prague-state_test-call_type_DELEGATECALL] ________
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xE9C75F1Ca00AB05473cA49e22dDA6ECb7273b655, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_calls.py:99: in test_tload_calls
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xE9C75F1Ca00AB05473cA49e22dDA6ECb7273b655, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 204740
Deploying contract with gas limit: 216746
--------------------------- Captured stdout teardown ---------------------------
Used balance=2.000043981600000187
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x61Aa66EeDf8Ac28A8C1D8819e237116a6431A90F, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x61Aa66EeDf8Ac28A8C1D8819e237116a6431A90F, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 330302
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000044973000000059
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xb7bdD06a6A5bCC71e147A2eE7eB1AF6b6BF72164, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xb7bdD06a6A5bCC71e147A2eE7eB1AF6b6BF72164, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 330302
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000044973000000059
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xD94da11cf9ddb37dfC1019E3357465ddf455d674, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xD94da11cf9ddb37dfC1019E3357465ddf455d674, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 329456
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000044930799999898
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xC8cD43c4370818e5f11035B01985102BF1a9020B, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xC8cD43c4370818e5f11035B01985102BF1a9020B, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 329456
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000044930799999898
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x876EaB5A22D13401E07F92Bfcbd40Df0b0a99d61, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x876EaB5A22D13401E07F92Bfcbd40Df0b0a99d61, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 330302
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000044973000000059
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x394eAdeEaDD63bE293387dA76D7D84e0BDD0Ea1B, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x394eAdeEaDD63bE293387dA76D7D84e0BDD0Ea1B, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 330302
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000044973000000059
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xa227defF8Db056690019A3c2c8cFdC1D4D338444, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xa227defF8Db056690019A3c2c8cFdC1D4D338444, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 329456
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000044930799999898
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x195778aAe189957298D6F8A51c677D8Cc8396090, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x195778aAe189957298D6F8A51c677D8Cc8396090, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 329456
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000044930799999898
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xf7425759B55F91fFAfa8122886942D17888F93c1, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xf7425759B55F91fFAfa8122886942D17888F93c1, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 114398
Deploying contract with gas limit: 333710
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045313800000057
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x531c184bB68E3cAe640616c716Fa8b8fAb65a3Fc, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x531c184bB68E3cAe640616c716Fa8b8fAb65a3Fc, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 114398
Deploying contract with gas limit: 333710
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045313800000057
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x8891E23194634A5B5DFb01Fb348dC115a2bdeAEf, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x8891E23194634A5B5DFb01Fb348dC115a2bdeAEf, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 114398
Deploying contract with gas limit: 332870
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045271799999913
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x5b820C89e5Bdd615Ca06307862b13Ca7726D927C, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x5b820C89e5Bdd615Ca06307862b13Ca7726D927C, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 114398
Deploying contract with gas limit: 332870
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045271799999913
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xEBDD0ddd440705F116c53E107Ef005CBfE6d1612, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xEBDD0ddd440705F116c53E107Ef005CBfE6d1612, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 338942
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045405000000054
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x23977e5c57bEf26C2c83BfB8a43e2761f1CB23e1, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x23977e5c57bEf26C2c83BfB8a43e2761f1CB23e1, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 338942
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045405000000054
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xD3e99550fD9033287CfC3094c8809ab910962b46, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xD3e99550fD9033287CfC3094c8809ab910962b46, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 338102
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045362999999909
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xc2e625ADbea5448B386FE1aFDA45b4aEF5ae96fc, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xc2e625ADbea5448B386FE1aFDA45b4aEF5ae96fc, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 338102
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045362999999909
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x88D214F0715Fa30331ABd274625dCD37cA0b4581, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x88D214F0715Fa30331ABd274625dCD37cA0b4581, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 338918
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045403799999955
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x10b2a09dB59ff42228098A92B3C96761Fe05C3Fc, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x10b2a09dB59ff42228098A92B3C96761Fe05C3Fc, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 338942
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045405000000054
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x1B4A2E7f344199Db8B2075d106eDa2aa2758947F, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x1B4A2E7f344199Db8B2075d106eDa2aa2758947F, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 338102
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045362999999909
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x45e7548bC19d05fe3F2a206FB20C8a008b87375e, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x45e7548bC19d05fe3F2a206FB20C8a008b87375e, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 110990
Deploying contract with gas limit: 338078
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045361800000032
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xDf9cAB8E58f3146C7D511e2C16d75a2Df83c8105, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xDf9cAB8E58f3146C7D511e2C16d75a2Df83c8105, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 114398
Deploying contract with gas limit: 342350
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045745800000052
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xd80E04c0d980EeAFB5B84221DA18cDAE3F688D41, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xd80E04c0d980EeAFB5B84221DA18cDAE3F688D41, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 114398
Deploying contract with gas limit: 342350
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045745800000052
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xfc41eD79Bd49d778144624574d08FEE874d67587, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xfc41eD79Bd49d778144624574d08FEE874d67587, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 114398
Deploying contract with gas limit: 341510
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045703799999908
_ test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x01D96CDDE024C0956B82d5511611cF085a5Cd24C, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tload_reentrancy.py:166: in test_tload_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x01D96CDDE024C0956B82d5511611cF085a5Cd24C, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 114398
Deploying contract with gas limit: 341510
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000045703799999908
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xe0B3B571c8298cdCd34BF2749BB5d3A1357e20c6, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xe0B3B571c8298cdCd34BF2749BB5d3A1357e20c6, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 484796
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000052979799999964
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x8265545f348be2Bf56c0F355342EbfbDe6e6E26C, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x8265545f348be2Bf56c0F355342EbfbDe6e6E26C, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 484796
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000052979799999964
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x9a3FC59e3DDc470aC3A7c214B7DeFe768a1e098c, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x9a3FC59e3DDc470aC3A7c214B7DeFe768a1e098c, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 483956
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000052937800000041
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x1d5604344350e60A7Ba01bB8F0786D437e5C2fc4, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x1d5604344350e60A7Ba01bB8F0786D437e5C2fc4, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 483956
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000052937800000041
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x37Ed6fEd5fE1EC3E5087D64d0eE38278C8086c13, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x37Ed6fEd5fE1EC3E5087D64d0eE38278C8086c13, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 484796
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000052979799999964
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x0F7973CF8645005CE2CdFE360E8dAFa67dc2486e, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x0F7973CF8645005CE2CdFE360E8dAFa67dc2486e, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 484796
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000052979799999964
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xb4C8fbFd1C3aF85a95C1e9027A40097E195702c0, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xb4C8fbFd1C3aF85a95C1e9027A40097E195702c0, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 483956
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000052937800000041
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xBa15447c495ce278e37444C61F49A9495C452beE, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xBa15447c495ce278e37444C61F49A9495C452beE, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 483956
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000052937800000041
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x60b75a0E765053a742264Af5AEbd3e547832FB5d, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x60b75a0E765053a742264Af5AEbd3e547832FB5d, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 122996
Deploying contract with gas limit: 488210
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053321400000028
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x7eE767e3dC04D9B7863a4E020a65546272957121, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x7eE767e3dC04D9B7863a4E020a65546272957121, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 122996
Deploying contract with gas limit: 488210
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053321400000028
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xfa51cA0Ca9aB95BD11527f47f2e301322Fb249F5, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xfa51cA0Ca9aB95BD11527f47f2e301322Fb249F5, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 122996
Deploying contract with gas limit: 487370
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053279400000106
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x9C71c50E627e839A7781c79F930ee2d6F91A76Fb, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x9C71c50E627e839A7781c79F930ee2d6F91A76Fb, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 122996
Deploying contract with gas limit: 487370
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053279400000106
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xEC0B9090F7A06b11560Fb158273A59992fef6F77, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xEC0B9090F7A06b11560Fb158273A59992fef6F77, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 493442
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053412600000025
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x242bbbEaFc50cdA48BB71D91D7E548E2AFcc8512, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x242bbbEaFc50cdA48BB71D91D7E548E2AFcc8512, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 493442
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053412600000025
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xe3d1FF50C87C7caF284327B1c4E1e41CfdbA5ED9, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xe3d1FF50C87C7caF284327B1c4E1e41CfdbA5ED9, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 492602
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053370000000053
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x4cC4C7D77fa4f400b8212DaB35Fae831c2EF6989, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x4cC4C7D77fa4f400b8212DaB35Fae831c2EF6989, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 492602
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053370000000053
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xcc4124c97753F5A68d3578f26A44E78d9D12FA6b, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xcc4124c97753F5A68d3578f26A44E78d9D12FA6b, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 493442
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053412600000025
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xEaF4eA2312CFE0a975dbaAaaCB0498C9C009c2ee, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xEaF4eA2312CFE0a975dbaAaaCB0498C9C009c2ee, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 493442
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053412600000025
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x92da264751C72c9D707B4edcFE7ab5241Bd97282, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x92da264751C72c9D707B4edcFE7ab5241Bd97282, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 492602
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053370000000053
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x2479c97C4d58A6B691048F46492AA831bb438729, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x2479c97C4d58A6B691048F46492AA831bb438729, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 119588
Deploying contract with gas limit: 492602
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053370000000053
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x3037E9316b2191Ce4E581583A914296A1C71d510, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x3037E9316b2191Ce4E581583A914296A1C71d510, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 122996
Deploying contract with gas limit: 496850
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053754000000072
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALLCODE] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xcfe168a99C9B70B18360eFa8Fe4F87AD66A09cAC, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xcfe168a99C9B70B18360eFa8Fe4F87AD66A09cAC, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 122996
Deploying contract with gas limit: 496850
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053754000000072
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_DELEGATECALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xd1f82C7f36eE5794b2B23d5F150c02b354B665Cd, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0xd1f82C7f36eE5794b2B23d5F150c02b354B665Cd, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 122996
Deploying contract with gas limit: 495986
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053710800000051
_ test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_STATICCALL] _
src/ethereum_test_rpc/rpc.py:209: in send_transaction
    self.post_request("sendRawTransaction", f"{transaction.rlp().hex()}")
src/ethereum_test_rpc/rpc.py:100: in post_request
    raise JSONRPCError(**response_json["error"])
E   ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x27Fa24df2700980ad009C8F65916f33D2dF9B1C8, maxFeePerGas: 10 baseFee: 100000000)

The above exception was the direct cause of the following exception:
tests/cancun/eip1153_tstore/test_tstore_reentrancy.py:226: in test_tstore_reentrancy
    state_test(env=Environment(), pre=pre, post=post, tx=tx)
src/pytest_plugins/execute/execute.py:321: in __init__
    execute.execute(fork=fork, eth_rpc=eth_rpc, engine_rpc=engine_rpc)
src/ethereum_test_execution/transaction_post.py:40: in execute
    eth_rpc.send_wait_transactions([tx.with_signature_and_sender() for tx in block])
src/ethereum_test_rpc/rpc.py:290: in send_wait_transactions
    self.send_transactions(transactions)
src/ethereum_test_rpc/rpc.py:219: in send_transactions
    return [self.send_transaction(tx) for tx in transactions]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:219: in <listcomp>
    return [self.send_transaction(tx) for tx in transactions]
            ^^^^^^^^^^^^^^^^^^^^^^^^^
src/ethereum_test_rpc/rpc.py:215: in send_transaction
    raise SendTransactionExceptionError(str(e), tx=transaction) from e
E   ethereum_test_rpc.rpc.SendTransactionExceptionError: JSONRPCError(code=-32000, message=max fee per gas less than block base fee: address 0x27Fa24df2700980ad009C8F65916f33D2dF9B1C8, maxFeePerGas: 10 baseFee: 100000000)
----------------------------- Captured stdout call -----------------------------
Deploying contract with gas limit: 122996
Deploying contract with gas limit: 496010
--------------------------- Captured stdout teardown ---------------------------
Used balance=1.000053711999999928
=========================== short test summary info ============================
FAILED tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_transaction_begin[fork_Prague-state_test]
FAILED tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_works[fork_Prague-state_test]
FAILED tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_other_after_tstore[fork_Prague-state_test]
FAILED tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_gasprice[fork_Prague-state_test]
FAILED tests/cancun/eip1153_tstore/test_basic_tload.py::test_basic_tload_after_store[fork_Prague-state_test]
FAILED tests/cancun/eip1153_tstore/test_tload_calls.py::test_tload_calls[fork_Prague-state_test-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tload_calls.py::test_tload_calls[fork_Prague-state_test-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tload_calls.py::test_tload_calls[fork_Prague-state_test-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tload_reentrancy.py::test_tload_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_RETURN-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_REVERT-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.REENTRANCY-call_return_OOG-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_RETURN-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_REVERT-call_type_STATICCALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_CALLCODE]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_DELEGATECALL]
FAILED tests/cancun/eip1153_tstore/test_tstore_reentrancy.py::test_tstore_reentrancy[fork_Prague-state_test-call_dest_type_CallDestType.EXTERNAL_CALL-call_return_OOG-call_type_STATICCALL]
================== 56 failed, 69 passed in 132.65s (0:02:12) ===================
